import app from '@adonisjs/core/services/app'
import env from '#start/env'
import { mkdir, writeFile, readFile, unlink } from 'node:fs/promises'
import { randomUUID } from 'node:crypto'
import { fileTypeFromBuffer } from 'file-type'
import type { AnyMessageContent } from '@whiskeysockets/baileys'

export const CS_MEDIA_LIMIT = 16 * 1024 * 1024
export type CsMedia = {
  id: string
  name: string
  size: number
  mime: string
  type: 'image' | 'video' | 'audio' | 'document'
  url: string
}
const extensions = new Set([
  'jpg',
  'png',
  'webp',
  'gif',
  'mp4',
  'mov',
  'mp3',
  'ogg',
  'm4a',
  'wav',
  'pdf',
  'doc',
  'docx',
  'xls',
  'xlsx',
  'ppt',
  'pptx',
  'zip',
])

export function csMediaPath(id: string) {
  if (!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(id))
    throw new Error('Lampiran tidak valid.')
  return app.makePath('storage', 'cs-media', `${id}.bin`)
}

export async function storeCsMedia(bytes: Buffer, originalName: string): Promise<CsMedia> {
  if (!bytes.length || bytes.length > CS_MEDIA_LIMIT)
    throw new Error('Ukuran file harus 1 byte–16 MB.')
  const name =
    originalName
      .replaceAll('\\', '/')
      .split('/')
      .pop()!
      .replace(/\p{Cc}/gu, '')
      .slice(-190) || 'Lampiran'
  const extension = name.split('.').pop()!.toLowerCase()
  const detected = await fileTypeFromBuffer(bytes).catch(() => undefined)
  let mime = detected?.mime || ''
  let ext = detected?.ext || ''
  if (!detected && ['txt', 'csv'].includes(extension)) {
    try {
      new TextDecoder('utf-8', { fatal: true }).decode(bytes)
    } catch {
      throw new Error('File teks tidak valid.')
    }
    if (bytes.includes(0)) throw new Error('File teks tidak valid.')
    ext = extension
    mime = ext === 'csv' ? 'text/csv' : 'text/plain'
  } else if (ext === 'cfb' && ['doc', 'xls', 'ppt'].includes(extension)) {
    ext = extension
    mime = {
      doc: 'application/msword',
      xls: 'application/vnd.ms-excel',
      ppt: 'application/vnd.ms-powerpoint',
    }[extension]!
  } else if (!extensions.has(ext)) throw new Error('Format file belum didukung.')
  const aliases: Record<string, string> = { jpeg: 'jpg', oga: 'ogg', qt: 'mov' }
  if ((aliases[extension] || extension) !== ext)
    throw new Error('Format dan ekstensi file tidak cocok.')
  const type = ['jpg', 'png', 'webp'].includes(ext)
    ? 'image'
    : ['mp4', 'mov'].includes(ext)
      ? 'video'
      : ['mp3', 'ogg', 'm4a', 'wav'].includes(ext)
        ? 'audio'
        : 'document'
  const id = randomUUID()
  await mkdir(app.makePath('storage', 'cs-media'), { recursive: true, mode: 0o700 })
  await writeFile(csMediaPath(id), bytes, { flag: 'wx', mode: 0o600 })
  return {
    id,
    name,
    size: bytes.length,
    mime,
    type,
    url: `${(env.get('APP_BASE_PATH') || '')}/api/media/${id}`,
  }
}

export async function removeCsMedia(id: string) {
  await unlink(csMediaPath(id))
}

/** Only IDs generated by the upload endpoint can resolve to a local file. */
export async function csOutgoingPayload(message: Record<string, any>): Promise<AnyMessageContent> {
  if (!message.media_upload_id) return { text: message.body }
  const bytes = await readFile(csMediaPath(message.media_upload_id))
  if (!bytes.length || bytes.length > CS_MEDIA_LIMIT) throw new Error('Lampiran tidak valid.')
  const caption = String(message.body || '')
  if (message.media_type === 'image') return { image: bytes, caption, mimetype: message.media_mime }
  if (message.media_type === 'video') return { video: bytes, caption, mimetype: message.media_mime }
  // Audio with a caption is sent as a document so the caption is not silently lost.
  if (message.media_type === 'audio' && !caption)
    return { audio: bytes, mimetype: message.media_mime, ptt: false }
  return {
    document: bytes,
    caption,
    mimetype: message.media_mime,
    fileName: message.media_name || 'Lampiran',
  }
}
