/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Account: () => import('#controllers/account_controller'),
  AiAccounts: () => import('#controllers/ai_accounts_controller'),
  Backup: () => import('#controllers/backup_controller'),
  Beta3: () => import('#controllers/beta3_controller'),
  ContactDirectory: () => import('#controllers/contact_directory_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Diagnostics: () => import('#controllers/diagnostics_controller'),
  InstagramContent: () => import('#controllers/instagram_content_controller'),
  Instagram: () => import('#controllers/instagram_controller'),
  Legal: () => import('#controllers/legal_controller'),
  Lines: () => import('#controllers/lines_controller'),
  Orders: () => import('#controllers/orders_controller'),
  PaymentMethods: () => import('#controllers/payment_methods_controller'),
  Production: () => import('#controllers/production_controller'),
  SkillEdits: () => import('#controllers/skill_edits_controller'),
  WorkspaceMedia: () => import('#controllers/workspace_media_controller'),
}
