/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Account: () => import('#controllers/account_controller'),
  Carts: () => import('#controllers/carts_controller'),
  ContactDirectory: () => import('#controllers/contact_directory_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Diagnostics: () => import('#controllers/diagnostics_controller'),
  Learning: () => import('#controllers/learning_controller'),
  Orders: () => import('#controllers/orders_controller'),
  PaymentMethods: () => import('#controllers/payment_methods_controller'),
  Production: () => import('#controllers/production_controller'),
  SkillEdits: () => import('#controllers/skill_edits_controller'),
  WorkspaceMedia: () => import('#controllers/workspace_media_controller'),
}
