import { middleware } from '#start/kernel'
import router from '@adonisjs/core/services/router'

const AccountController = () => import('#controllers/account_controller')
const DashboardController = () => import('#controllers/dashboard_controller')
const PaymentMethodsController = () => import('#controllers/payment_methods_controller')
const CartsController = () => import('#controllers/carts_controller')
const ProductionController = () => import('#controllers/production_controller')
const OrdersController = () => import('#controllers/orders_controller')
const ContactDirectoryController = () => import('#controllers/contact_directory_controller')
const SkillEditsController = () => import('#controllers/skill_edits_controller')
const LearningController = () => import('#controllers/learning_controller')
const LeanController = () => import('#controllers/lean_controller')
const Beta3Controller = () => import('#controllers/beta3_controller')
const LinesController = () => import('#controllers/lines_controller')
const AiAccountsController = () => import('#controllers/ai_accounts_controller')

router.get('/login', [AccountController, 'login']).as('account.login')
router.post('/login', [AccountController, 'loginPost'])
router.get('/setup', [AccountController, 'setup']).as('account.setup')
router.post('/setup', [AccountController, 'setupPost'])
// Dedicated expiring bearer, fixed workspace; works without session/account or app DB middleware.
router.get('/api/ops/diagnostics', [() => import('#controllers/diagnostics_controller'), 'show'])
router.get('/auth/callback', [AccountController, 'callback']).as('account.callback')

router
  .group(() => {
    router.get('/', [DashboardController, 'index']).as('dashboard')
    router.get('/settings', [DashboardController, 'settingsPage']).as('settings')
    router.get('/orders', [OrdersController, 'page']).as('orders')
    router.get('/lean', [LeanController, 'page']).as('lean')
    router.get('/api/lean/catalog', [LeanController, 'catalog'])
    router.post('/api/lean/catalog', [LeanController, 'importCatalog'])
    router.post('/api/lean/catalog/sync', [LeanController, 'syncCatalog'])
    router.get('/api/lean/examples', [LeanController, 'examples'])
    router.post('/api/lean/examples', [LeanController, 'addExample'])
    router.delete('/api/lean/examples/:id', [LeanController, 'removeExample'])
    router.get('/api/lean/orders', [LeanController, 'orders'])
    router.post('/api/lean/orders/:id/approve', [LeanController, 'approveOrder'])
    router.post('/api/lean/orders/:id/paid', [LeanController, 'paidOrder'])
    router.post('/api/lean/orders/:id/cancel', [LeanController, 'cancelOrder'])
    router.post('/api/lean/orders/:id/resend-group', [LeanController, 'resendGroup'])
    router.get('/api/lean/mcp', [LeanController, 'mcp'])
    router.post('/api/lean/mcp', [LeanController, 'saveMcp'])
    router.get('/api/lean/room', [LeanController, 'room'])
    router.post('/api/lean/room/spec', [LeanController, 'saveSpec'])
    router.get('/api/lean/customer', [LeanController, 'customer'])
    router.post('/api/lean/customer', [LeanController, 'saveCustomer'])
    // Beta 3 — rute terisolasi
    router.get('/beta3', [Beta3Controller, 'page']).as('beta3')
    router.get('/api/beta3/catalog', [Beta3Controller, 'catalog'])
    router.post('/api/beta3/catalog', [Beta3Controller, 'importCatalog'])
    router.post('/api/beta3/catalog/sync', [Beta3Controller, 'syncCatalog'])
    router.get('/api/beta3/examples', [Beta3Controller, 'examples'])
    router.post('/api/beta3/examples', [Beta3Controller, 'addExample'])
    router.delete('/api/beta3/examples/:id', [Beta3Controller, 'removeExample'])
    router.get('/api/beta3/orders', [Beta3Controller, 'orders'])
    router.post('/api/beta3/orders/:id/approve', [Beta3Controller, 'approveOrder'])
    router.post('/api/beta3/orders/:id/paid', [Beta3Controller, 'paidOrder'])
    router.post('/api/beta3/orders/:id/cancel', [Beta3Controller, 'cancelOrder'])
    router.post('/api/beta3/orders/:id/resend-group', [Beta3Controller, 'resendGroup'])
    router.get('/api/beta3/mcp', [Beta3Controller, 'mcp'])
    router.post('/api/beta3/mcp', [Beta3Controller, 'saveMcp'])
    router.get('/api/beta3/room', [Beta3Controller, 'room'])
    router.post('/api/beta3/room/spec', [Beta3Controller, 'saveSpec'])
    router.get('/api/beta3/skill', [Beta3Controller, 'skill'])
    router.post('/api/beta3/skill/update', [Beta3Controller, 'updateSkill'])
    router.get('/api/beta3/recap', [Beta3Controller, 'recapStatus'])
    router.post('/api/beta3/recap', [Beta3Controller, 'startRecap'])
    router.get('/api/beta3/customer', [Beta3Controller, 'customer'])
    router.post('/api/beta3/customer', [Beta3Controller, 'saveCustomer'])
    router.get('/api/lines', [LinesController, 'index'])
    router.post('/api/lines', [LinesController, 'store'])
    router.post('/api/lines/:id/disconnect', [LinesController, 'disconnect'])
    router.get('/api/ai/accounts', [AiAccountsController, 'index'])
    router.get('/api/ai/orchestra', [AiAccountsController, 'orchestra'])
    router.post('/api/ai/accounts', [AiAccountsController, 'store'])
    router.post('/api/ai/accounts/:id/update', [AiAccountsController, 'update'])
    router.post('/api/ai/accounts/order', [AiAccountsController, 'order'])
    router.delete('/api/ai/accounts/:id', [AiAccountsController, 'destroy'])
    router.get('/api/ai/accounts/:id/login', [AiAccountsController, 'loginStatus'])
    router.post('/api/ai/accounts/:id/login', [AiAccountsController, 'loginStart'])
    router.post('/api/ai/accounts/:id/verify', [AiAccountsController, 'loginVerify'])
    router.get('/contacts', [ContactDirectoryController, 'page']).as('directory')
    router.get('/api/contact-directory', [ContactDirectoryController, 'index'])
    router.get('/api/contact-directory/export', [ContactDirectoryController, 'export'])
    router.get('/api/orders', [OrdersController, 'index'])
    router.get('/api/orders/routing', [OrdersController, 'routing'])
    router.put('/api/orders/routing', [OrdersController, 'saveRouting'])
    router.post('/api/orders/groups/refresh', [OrdersController, 'refreshGroups'])
    router.put('/api/orders/:id/operations', [OrdersController, 'save'])
    router.post('/api/orders/:id/retry-group', [OrdersController, 'retry'])
    router.post('/api/orders/:id/acknowledge-group', [OrdersController, 'acknowledge'])
    router.get('/api/orders/:id/history', [OrdersController, 'history'])
    router.post('/logout', [AccountController, 'logout']).as('account.logout')
    router.get('/api/status', [DashboardController, 'status'])
    router.get('/api/version', [DashboardController, 'version'])
    router.get('/api/access', [DashboardController, 'access'])
    router.post('/api/access/domain', [DashboardController, 'setAccessDomain'])
    router.post('/api/access/domain/unset', [DashboardController, 'unsetAccessDomain'])
    router.get('/api/workspace', ({ response }) => response.noContent())
    router.get('/api/chats/cleanup/contact', [DashboardController, 'contactCleanupPreview'])
    router.get('/api/chats/cleanup', [DashboardController, 'chatCleanupStatus'])
    router.post('/api/chats/cleanup', [DashboardController, 'chatCleanup'])
    router.get('/media/*', [() => import('#controllers/workspace_media_controller'), 'show'])
    router.get('/api/cart', [CartsController, 'index'])
    router.post('/api/cart/:action', [CartsController, 'mutate'])
    router.get('/api/ai/usage', [DashboardController, 'usage'])
    router.get('/api/ai/quotas', [DashboardController, 'quotas'])
    router.get('/api/ai/trace', [DashboardController, 'trace'])
    router.get('/api/contacts', [DashboardController, 'contactsList'])
    router.get('/api/search', [DashboardController, 'searchMessages'])
    router.post('/api/contacts/read', [DashboardController, 'contactRead'])
    router.post('/api/contacts/mode', [DashboardController, 'contactMode'])
    router.get('/api/ai/exclusions', [DashboardController, 'aiExclusions'])
    router.post('/api/contacts/exclusion', [DashboardController, 'contactExclusion'])
    router.get('/api/messages', [DashboardController, 'messages'])
    router.post('/api/messages/send', [DashboardController, 'sendMessage'])
    router.get('/api/media/:id', [DashboardController, 'media'])
    router.post('/api/messages/reaction', [DashboardController, 'reactMessage'])
    router.post('/api/connect', [DashboardController, 'connect'])
    router.post('/api/disconnect', [DashboardController, 'disconnect'])
    router.post('/api/settings', [DashboardController, 'settings'])
    router.get('/api/settings/production', [ProductionController, 'index'])
    router.put('/api/settings/production', [ProductionController, 'save'])
    router.get('/api/settings/payments', [PaymentMethodsController, 'index'])
    router.post('/api/settings/payments', [PaymentMethodsController, 'save']).as('payments.create')
    router
      .put('/api/settings/payments/:id', [PaymentMethodsController, 'save'])
      .as('payments.update')
    router.delete('/api/settings/payments/:id', [PaymentMethodsController, 'delete'])
    router.delete('/api/settings/skills/:id', [DashboardController, 'skillDelete'])
    router.post('/api/settings/skill-edits', [SkillEditsController, 'create'])
    router.get('/api/settings/skill-edits/:id', [SkillEditsController, 'show'])
    router.get('/api/settings/skills/:id/download', [DashboardController, 'skillDownload'])
    router.get('/api/ai/evaluations', [DashboardController, 'evaluations'])
    router.get('/api/ai/learning', [LearningController, 'index'])
    router.put('/api/ai/learning', [LearningController, 'save'])
    router.post('/api/ai/learning/:id/rollback', [LearningController, 'rollback'])
    router.get('/api/ai/oauth/status', [DashboardController, 'oauthStatus'])
    router.post('/api/ai/oauth/start', [DashboardController, 'oauthStart'])
    router.get('/api/ai/codex/status', [DashboardController, 'codexStatus'])
    router.get('/api/ai/claude/oauth/status', [DashboardController, 'claudeOauthStatus'])
    router.post('/api/ai/claude/oauth/start', [DashboardController, 'claudeOauthStart'])
    router.post('/api/ai/claude/oauth/verify', [DashboardController, 'claudeOauthVerify'])
    router.get('/api/ai/claude/status', [DashboardController, 'claudeStatus'])
    router.get('/api/mcp/oauth/status', [DashboardController, 'mcpOauthStatus'])
    router.post('/api/mcp/oauth/start', [DashboardController, 'mcpOauthStart'])
    router.post('/api/mcp/oauth/verify', [DashboardController, 'mcpOauthVerify'])
    router.get('/oauth/mcp/callback/shared/:slug', [DashboardController, 'sharedMcpCallback'])
    router
      .get('/oauth/mcp/callback/:loginId', [DashboardController, 'mcpOauthCallback'])
      .as('mcp.callback')
    router
      .get('/oauth/mcp/callback/:loginId/:callbackId', [DashboardController, 'mcpOauthCallback'])
      .as('mcp.callback.withId')
    router.post('/api/settings/mcp', [DashboardController, 'mcpCreate'])
    router.delete('/api/settings/mcp/:slug', [DashboardController, 'mcpDelete'])
  })
  .use(middleware.accountAuth())
  .use(middleware.workspace())
